inputs:
  model_name: 'hyperpose'
  mode: 'train'
  backbone_path: './models/backbones/efficient-net-b0.pth'
  dataset_path: '/home/dev/Data/7scenes'
  labels_file: './datasets/7Scenes/abs_7scenes_pose.csv_heads_train.csv'
  checkpoint_path: null
  experiment: null
  output_path: '/media/dev/storage1/hyperpose_output'

general:
  n_freq_print: 5
  n_freq_checkpoint: 5
  start_save_epoch: 10 #1 #10
  n_workers: 4
  devices_id: [0, 1, 2]
  batch_size: 8
  n_epochs: 75 #25 #75

hyperpose:
  loss:
    learnable: False #True
    s_x: -3
    s_q: -6.5
    norm: 2
  lr: 1e-3
  weight_decay: 1e-4
  eps: 1e-10
  lr_scheduler_gamma: 0.75
  lr_scheduler_step_size: 100
  num_encoder_layers: 6
  dim_feedforward: 256
  hidden_dim: 256
  hyper_dim_t: 256
  hyper_dim_rot: 512
  dropout: 0.1
  nheads: 4
  freeze: False
  use_quat_mul: False
  reduction:
    t: 'reduction_4'
    q: 'reduction_3'
  freeze_exclude_phrase: ['regressor_head_t', 'hypernet_t_fc_h1', 'hypernet_t_fc_h2', 'hypernet_t_fc_o']
#  freeze_exclude_phrase: ['hypernet_rot_fc_h1', 'hypernet_rot_fc_h2', 'hypernet_rot_fc_o']